### ISSUE TITLE
Version 1.2 won't works with node JS

### ISSUE THREAD

**Issue by pgn-vole** [tanakahisateru/js-markdown-extra#14]
I was using this lib on server-side with node js without any issues. 
But the new version won't work at all.
The markdown seems completely ignored by the lib.

**Comment by tanakahisateru** [comment]
Which version of Node.js do you use? I tried to run with v0.8.11 and it displayed expected result (same as demo page's one).

If you are using the same version, can you show me your usage of this lib with your failed text?

**Comment by pgn-vole** [comment]
I just tried with the last version of node and I've the same issue.
I'm on windows maybe that could help you.
I think there is something wrong with the line break parsing.

this works:

```
xxxxx
=======
```

this doesn't

```
xxxxx
=======

```

**Comment by tanakahisateru** [comment]
Well, I guess that it caused by CRLF. My test code

``` javascript
var md = require('./js-markdown-extra.js'); // this.Markdown = Markdown;

console.log("Line ending with LF:\n", md.Markdown(
    "xxxx\n" +
    "====\n"
));

console.log("Line ending with CRLF:\n", md.Markdown(
    "xxxx\r\n" +
    "====\r\n"
));

console.log("No CRLF before EOF:\n", md.Markdown(
    "xxxx\r\n" +
    "===="
));
```

gives

```
Line ending with LF:
 <h1>xxxx</h1>

Line ending with CRLF:
 <p>xxxx
====</p>

No CRLF before EOF:
 <h1>xxxx</h1>
```

Node.js has no flag to change line ending character like "b" or "t".

http://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback

Can you get the expected result with below?

``` javascript
var md_text = Markdown(source_text.replace(/\r(?=\n)/g, ''));
```

**Comment by pgn-vole** [comment]
Yes it works fine on my example

**Comment by tanakahisateru** [comment]
Congrats, @pgn-vole 

I removed `defect` tag from this issue and closed.

I think that trimming line ending characters is not suitable as the responsibility of this module, rather it's something of file IO. Compatibility with original implementation is more important than it.
