### ISSUE TITLE
Code will not pase if indented with tab character

### ISSUE THREAD

**Issue by Zyber17** [tanakahisateru/js-markdown-extra#16]
Code ran though the parser indented with the actual tab character (rather than of four spaces) is interpreted just as text rather than code.

**Comment by tanakahisateru** [comment]
Replacing process of TAB to 4 white spaces was passed trough after the 2nd TAB character.
Seems fixed. @Zyber17 please check it again.

**Comment by Zyber17** [comment]
Yep, that fixed it! Thanks!
