### ISSUE TITLE
Definition lists with multiple items are converted to multiple definition lists instead.

### ISSUE THREAD

**Issue by jmcmanus** [tanakahisateru/js-markdown-extra#23]
.. If the first item in the list is preceded by a blank line. For example:

``` markdown
term

 : definition

term

 : definition
```

Becomes:

``` html
<dl>
<dt>term</dt>
<dd>
<p>definition</p>
</dd>
</dl>

<dl>
<dt>term</dt>
<dd>
<p>definition</p>
</dd>
</dl>
```

It wraps the definitions in `<p>` tags correctly, but doesn't recognize that they're part of the same list. The fix is simple enough though. There's an extra space in your regex:

``` js
'(?:\\S.*\\n )+?' + // defined term
```

I believe it should be:

``` js
'(?:\\S.*\\n)+?' + // defined term
```

**Comment by tanakahisateru** [comment]
Thanks,
I will fix soon.

**Comment by tanakahisateru** [comment]
Both lists of your example have been unified. Thanks so much!
