### ISSUE TITLE
Incomplete emphasis/strong tags causes deleted and duplicated text

### ISSUE THREAD

**Issue by adamaveray** [tanakahisateru/js-markdown-extra#24]
If only half of an emphasis/strong tag is entered, the text before it is deleted, and the text after it is duplicated.

``` markdown
One two _three four five
```

should render as

``` html
<p>One two _three four five</p>
```

but instead renders as 

``` html
<p>three four five.three four five</p>
```

**Comment by tanakahisateru** [comment]
I've started to work with it. Thanks for your report.

**Comment by tanakahisateru** [comment]
The problem was fixed.

JavaScript's evaluation process of :

``` javascript
text_stack[0] += text_stack.shift();
```

is not same as PHP's :

``` php
$text_stack[0] .= array_shift($text_stack);
```
