### ISSUE TITLE
Script tag in fenced code block is not escaped.

### ISSUE THREAD

**Issue by bigwhoop** [tanakahisateru/js-markdown-extra#27]
Normal code blocks work as expected:

```
console.log(Markdown("foo\r\n\r\n    <script>console.log('heya');</scr" + "ipt>"));
```

... leads to ...

```
<p>foo</p>
<pre><code>&lt;script&gt;console.log('heya');&lt;/script&gt;
</code></pre>
```

The `script` tag is properly escaped. But when using fenced code blocks, that tag is not escaped:

```
console.log(Markdown("~~~\r\n<script>console.log('heya');</scr" + "ipt>\r\n~~~"));
```

... leads to ...

```
<pre><code><br /><br /><script>console.log('heya');</script>
</code></pre>
```

I'll try to come up with a patch, but I wasn't successful yet. Any help is appreciated.

Best
Phil

**Comment by tanakahisateru** [comment]
It looks a complex bug.

I'm researching and guessing that contents of fenced code block are now unexpectedly converted to hash-code in `MarkdownExtra_Parser.prototype._hashHTMLBlocks_inMarkdown`. It's wrong conversion. An indented code blocks are retained correctly.

I guess that something bad is around the line of  `// Check for: Fenced code block marker.`.

Tracing call of `doFencedCodeBlocks`, markdown-text was passed to it as:

```
~~~~
B123(some random hash code)
~~~~
```

Such hashed-codes cannot be escaped in `doFencedCodeBlocks` then they would be expanded to HTML tag without sanitizing later.

I will continue to research.

**Comment by tanakahisateru** [comment]
Ah,

``` diff
-        else if(tag.match(new RegExp('^\\n?[ ]{0,' + (indent + 3) * '}~'))) {
+        else if(tag.match(new RegExp('^\\n?[ ]{0,' + (indent + 3) + '}~'))) {
```

I can't believe why JavaScript could pass that code... :anguished: 

All new tests was cleared. Thanks for your reporting.

**Comment by bigwhoop** [comment]
Thank you!
