### ISSUE TITLE
Script tag in inline code block is not escaped (after #27)

### ISSUE THREAD

**Issue by bigwhoop** [tanakahisateru/js-markdown-extra#30]
Hi!

I think the fix for #27 (which worked) introduced a new bug with inline code blocks.

```
input     :  `<script></script>`
expected  :  <p><code>&lt;script&gt;&lt;/script&gt;</code></p>
actual    :  <p>`</p>\n\n<script></script>\n\n<p>`</p>
```

Can you confirm this?

Many thanks!
Phil

**Comment by tanakahisateru** [comment]
It seems because of #28, in 62c5887 a trick to avoid JS regexp's weakness but it ignores too many cases. I can fix it now.

**Comment by tanakahisateru** [comment]
Test https://github.com/tanakahisateru/js-markdown-extra/blob/d2003019554868f9ccaee561b5fc1963ed642338/tests/sanitize.js#L54 ...works fine.
Thanks, and sorry not to have enough tests.

**Comment by bigwhoop** [comment]
Thank you!

>  Thanks, and sorry not to have enough tests.

You don't have to be sorry. You don't have any obligations. :)
