### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by raphinesse** [tanakahisateru/js-markdown-extra#31]
[The Demo](http://tanakahisateru.github.io/js-markdown-extra/demo.html) is not working in current Chrome and probably other current Browsers too. That is because you serve the JavaScript directly from `raw.github.com`. You should probably serve it from github pages where your HTML/CSS is located too.

See [related issue in Chromium tracker](https://code.google.com/p/chromium/issues/detail?id=180007) for more information.

**Comment by tanakahisateru** [comment]
Thanks reporting!
