### ISSUE TITLE
Unrecognized inline tags in paragraphs

### ISSUE THREAD

**Issue by michelf** [tanakahisateru/js-markdown-extra#36]
When writing HTML tags inside a paragraph, the tag isn't seen as a tag when it contains attributes. For instance, this will not work (the tag gets escaped):

```
<img src="blah.png" class="abc">
```

But interestingly, this will work and pass the tag as-is in the HTML output:

```
<img>
```

The problem seems to be in `parseSpan`. You're suing `(?=` in two places for non-capture blocks. The original in PHP Markdown Extra uses `(?>` which consumes the input, unlike `(?=`. As a general rule you should probably use `(?:` to replace `(?>` in JS rather than the non-consuming `(?=`.

Reference to PHP's once-only patterns `(?>`: http://www.php.net/manual/en/regexp.reference.onlyonce.php

**Comment by tanakahisateru** [comment]
I'll check it soon.

**Comment by tanakahisateru** [comment]
I tried `(?:` instead of PHP's `(?>`, then it worked as expected. Thanks lot!
Indeed, you are the author of the original version.
